steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/superb-robot-371714/kertolaskut', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/superb-robot-371714/kertolaskut']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'kertolaskut', '--image', 'gcr.io/superb-robot-371714/kertolaskut', '--platform', 'managed']